# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Tribuo CI (Windows x86_64, Java SE 17, 21)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        # test against supported LTS versions and latest
        java: [ 17 ]
    name: Windows Java SE ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Oracle Java SE
        uses: oracle-actions/setup-java@v1
        with:
          website: oracle.com
          release: ${{ matrix.java }}
      - name: Build with Maven
        run: mvn clean install

    
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build and Push Docker Image
        run: |
              docker buildx create --use
              docker buildx build --platform linux/amd64,linux/arm64 -t your-image:latest .
              docker buildx imagetools inspect your-image:latest
              # Add additional steps as needed for your workflow
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
              
